#include "ib2slurm.h"

nn_map_t* node_name_map = NULL;

void switch_iter_func(ibnd_node_t* node, void* curry)
{
    ibnd_port_t* port;
    int p = 0;

    fprintf(stdout, "SwitchName=%" PRIx64, node->guid);

    //char* switchname = node_name(node);
    //fprintf(stdout, "SwitchName=%s", switchname);
    //free(switchname);

    fprintf(stdout, " Switches=");
    for(p = 1; p <= node->numports; p++) {
        if(node->type == IB_NODE_SWITCH) {
            port = node->ports[p];

            if(port && port->remoteport) {
                fprintf(stdout, "%" PRIx64 ", ", port->remoteport->guid);

//                char* remoteswitch = node_name(port->remoteport->node);
//                fprintf(stdout, "%s,", remoteswitch);
//                free(remoteswitch);
            }
        }
    }

    fprintf(stdout, " Nodes=");
    for(p = 1; p <= node->numports; p++) {
        if(node->type == IB_NODE_CA) {
            port = node->ports[p];

            if(port && port->remoteport) {
                char* remotenode = node_name(port->remoteport->node);
                fprintf(stdout, "%s,", remotenode);
                free(remotenode);
            }
        }
    }

    fprintf(stdout, "\n");
}

char* node_name(ibnd_node_t* node)
{
    char* buf = NULL;

    if(node == NULL) {
        fprintf(stderr, "Attempted to get a node name from an invalid node.");
        exit(EXIT_FAILURE);
    }

    buf = remap_node_name(node_name_map, node->guid, node->nodedesc);

    return buf;
}

int main(int argc, char** argv)
{
    struct ibnd_config config = {0};
    ibnd_fabric_t* fabric = NULL;
    char* node_name_map_file = NULL;

    char* ibd_ca = NULL;
    int ibd_ca_port = 0;

    int option_index = 0;
    int c;
    static struct option long_options[] = {
        {"node-name-map", 1, 0, 'm'},
        {NULL, 0, NULL, 0}
    };

    while((c = getopt_long(argc, argv, "m:", long_options, &option_index)) != -1) {
        switch(c) {
            case 'm':
                node_name_map_file = strdup(optarg);
                break;
        }
    }

    node_name_map = open_node_name_map(node_name_map_file);

    if((fabric = ibnd_discover_fabric(ibd_ca, ibd_ca_port, NULL, &config)) == NULL) {
        fprintf(stderr, "IB discover failed.\n");
        exit(EXIT_FAILURE);
    }

    fprintf(stdout, "# topology.conf\n"
            "# Switch Configuration\n#\n"
            "# Generated by ib2slurm <http://github.com/hpc/ib2slurm>\n#\n");

    ibnd_iter_nodes_type(fabric, switch_iter_func, IB_NODE_SWITCH, NULL);

    ibnd_destroy_fabric(fabric);
    close_node_name_map(node_name_map);

    exit(EXIT_SUCCESS);
}

/* EOF */
